### ISSUE TITLE
404 

### ISSUE THREAD

**Issue by ungaungaungaunga** [devinsmith/rca-cambio-linux#14] opened 2024-05-24 05:05 UTC
respond.xml Cannot download All mirrors tried.

Everything else downloaded in. from Sudo Yum install gcc-gcc+ libx11-devel libXi-devel lib Xrandr-devel git

**Comment by adrcunha** [comment] 2024-08-28 13:38
I'm not a Fedora user, so I don't know why the command fails and I can't reproduce it. In any case, assuming that the wrong package names "gcc-gcc+" and "lib Xrandr-devel" were just typos, and although I didn't find an exact match for the error message you mentioned, a Google search suggests several possibilities and answers (e.g. your repository is broken) so I would just go through those.

**Comment by devinsmith** [comment] 2024-08-30 04:25
Closing as resolution suggested.

**Closed as completed by devinsmith** 2024-08-30 04:25 UTC
